name: PharmaVend-Workflow
on:
  push:
    branches: [ "master" ]

jobs:
  pharmavend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PharmaVend-server/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          submodules: recursive

      - name: Install Composer Dependencies
        run: |
          composer update
          composer install

      - name: Prepare Environment
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "APP_KEY=base64:$(php artisan key:generate --show)" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=${{ github.workspace }}/PharmaVend-server/database/database.sqlite" >> .env
          echo "JWT_SECRET=$(php artisan jwt:secret --show)" >> .env  

      - name: Migrate and Seed Database
        run: | 
         php artisan migrate --force
         php artisan db:seed --force

      - name: Run Laravel Tests
        run: php artisan test



  pharmavend-cd:
    needs: pharmavend-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PharmaVend-server/

    steps: 
    - uses: actions/checkout@v4.2.0
      with:
          submodules: false
          sparse-checkout: |
           PharmaVend-server
          sparse-checkout-cone-mode: false
          
    - name: Debug Checkout Path
      run: |
        echo "Current working directory:"
        pwd
        echo "Listing files in working directory:"
        ls -la
        echo "Listing contents inside PharmaVend-server:"
        ls -la PharmaVend-server/


    - name: Deployment
      uses: easingthemes/ssh-deploy@main
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        source: "./"
        target: "/var/www/html/PharmaVend-server/"
        SCRIPT_AFTER: |
         echo "Starting deployment verification..."
         cd /var/www/html/PharmaVend-server/
         sudo touch deployment_successful_1.txt
         sudo echo "Deployment completed successfully" > deployment_successful.txt
         ls -la /var/www/html/PharmaVend-server/
