name: PharmaVend-Workflow
on:
  push:
    branches: [ "master" ]
jobs:
  pharmavend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PharmaVend-server/
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12' # Specify your PHP version here
          extensions: mbstring, xml, ctype, json, sqlite3, pdo_sqlite
          coverage: none
          
      - name: Install Composer Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Set up SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "DB_CONNECTION=sqlite" > .env
          echo "DB_DATABASE=${{ github.workspace }}/PharmaVend-server/database/database.sqlite" >> .env
          php artisan migrate
          php artisan db:seed # If you use seeders

      - name: Run PHPUnit Tests
        run: php artisan test

  pharmavend-cd:
    needs: pharmavend-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Step or Additional Commands
        run: echo "Deploy your application or other steps"
