name: PharmaVend-Workflow
on:
  push:
    branches: [ "master" ]

jobs:
  pharmavend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PharmaVend-server/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Composer Dependencies
        run: |
          composer update
          composer install

      - name: Prepare Environment
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "APP_ENV=testing" >> .env  # Set the environment to testing
          echo "APP_KEY=base64:$(php artisan key:generate --show)" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=${{ github.workspace }}/PharmaVend-server/database/database.sqlite" >> .env
          echo "JWT_SECRET=$(php artisan jwt:secret --show)" >> .env  # Ensure the JWT secret is set

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test

  pharmavend-cd:
    needs: pharmavend-ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Step or Additional Commands
        run: echo "Deploy your application or other steps"
