name: PharmaVend-Workflow
on:
  push:
    branches: [ "master" ]

jobs:
  pharmavend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PharmaVend-server/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Composer Dependencies
        run: |
          composer update
          composer install

      - name: Prepare Environment
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "APP_KEY=base64:$(php artisan key:generate --show)" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=${{ github.workspace }}/PharmaVend-server/database/database.sqlite" >> .env
          echo "JWT_SECRET=$(php artisan jwt:secret --show)" >> .env  

      - name: Migrate and Seed Database
        run: | 
         php artisan migrate --force
         php artisan db:seed --force

      - name: Run Laravel Tests
        run: php artisan test


  pharmavend-cd:
    needs: pharmavend-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PharmaVend-server/

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - uses: appleboy/ssh-action@master 
        with: 
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/PharmaVend-server/
            sudo git pull origin
            sudo php artisan migrate
            sudo composer install
     
    

