name: PharmaVend-Workflow
on:
  push:
    branches: [ "master" ]
jobs:
  pharmavend-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Switching to server directory
      working-directory: PharmaVend-server/
    - uses: nathanheffley/laravel-phpunit-action@master
    
    
        
  pharmavend-cd:
     needs: pharmavend-ci
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
       
