name: PharmaVend-Workflow
on:
  push:
    branches: [ "master" ]

jobs:
  pharmavend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PharmaVend-server/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          submodules: recursive

      - name: Install Composer Dependencies
        run: |
          composer update
          composer install

      - name: Prepare Environment
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "APP_KEY=base64:$(php artisan key:generate --show)" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=${{ github.workspace }}/PharmaVend-server/database/database.sqlite" >> .env
          echo "JWT_SECRET=$(php artisan jwt:secret --show)" >> .env  

      - name: Migrate and Seed Database
        run: | 
         php artisan migrate --force
         php artisan db:seed --force

      - name: Run Laravel Tests
        run: php artisan test



  pharmavend-cd:
    needs: pharmavend-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PharmaVend-server/

    # steps: 
    # - name: Checkout PharmaVend-server subdirectory only
    #   uses: actions/checkout@v4.2.0
    #   with:
    #       submodules: false
    #       sparse-checkout: |
    #         PharmaVend-server
    #       sparse-checkout-cone-mode: false

    # - name: Move contents to correct directory
    #   run: |
    #       echo "Moving PharmaVend-server contents..."
    #       mv ${{ github.workspace }}/PharmaVend-server/* ${{ github.workspace }}/ || true
    #       rm -rf ${{ github.workspace }}/PharmaVend-server || true
    #       echo "Listing contents after moving:"
    #       ls -R ${{ github.workspace }}

    # - name: Verify Repository Contents
    #   run: |
    #       echo "Checking current directory:"
    #       pwd
    #       echo "Listing contents of current directory:"
    #       ls -R

    # - name: Deployment
    #   uses: easingthemes/ssh-deploy@main
    #   env: 
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #     source: "${{ github.workspace }}/"
    #     target: "/var/www/html/PharmaVend-server"
    #     SCRIPT_AFTER: |
    #       echo "Starting deployment verification..."
    #       cd /var/www/html/PharmaVend-server/
    #       sudo touch deployment_successful_1.txt
    #       sudo echo "Deployment completed successfully" > deployment_successful.txt
    #       ls -la /var/www/html/PharmaVend-server/
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - uses: appleboy/ssh-action@master 
        with: 
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/PharmaVend-server/
            sudo git pull origin
     
    

