name: PharmaVend-Workflow
on:
  push:
    branches: [ "master" ]
jobs:
  pharmavend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PharmaVend-server/
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12' # Specify your PHP version here
          extensions: mbstring, xml, ctype, json, sqlite3, pdo_sqlite
          coverage: none
          
      - name: Install Composer Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare Environment
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "APP_ENV=local" >> .env  # Explicitly set the environment to local
          echo "APP_KEY=base64:$(php artisan --no-ansi key:generate --show)" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/home/runner/work/PharmaVend/PharmaVend/PharmaVend-server/database/database.sqlite" >> .env
      - name: Migrate Database
        run: php artisan migrate --force  # Use --force to bypass the production warning
      - name: Seed Database
        run: php artisan db:seed --force  # Use --force if seeding is necessary
      - name: Run Tests
        run: php artisan test

  pharmavend-cd:
    needs: pharmavend-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Step or Additional Commands
        run: echo "Deploy your application or other steps"
